# config for training MB-MelGan:
data:
  dataset: "LJSpeech"
  path: "../../projects/vocoder/data/LJSpeech-1.1"
  test_wav:
    "test1": "LJ001-0002"
    "test2": "LJ001-0013"
    "test3": "LJ001-0004"
    "test4": "LJ001-0006"
    "test5": "LJ001-0011"
  sample_rate: 16000 # target sample rate
  crop_len: 16000
  batch_size: 16
  num_workers: 4 # num_workers > 0 doesn't work in Windows

mel:
    nwin: 800
    hop: 200
    nfft: 1024
    mels: 80

melgan:
    bands: 1
    channels: 512

pqmf:
    cutoff_ratio: 0.15 # or null to automatically find the optimal value
    beta: 9.0
    length: 63
    
iters_pretrain: 200000
learning_rate: 1e-4
device: "cuda:0"
seed: 77
